variable "nic_name" {}
variable "nic_location" {}
variable "nic_rg_name" {}
variable "pip_name" {}
variable "pip_rgname" {}
variable "pip_location" {}
variable "pip_allmet" {}
variable "vm_name" {}
variable "vm_rgname" {}
variable "vm_location" {}
variable "vm_size" {}
variable "image_publisher" {}
variable "image_offer" {}
variable "image_sku" {}
variable "image_version" {}